export const TYPES = {
  HANDLE_CONNECTION: "HANDLE_CONNECTION",
  HANDLE_DISCONNECT: "HANDLE_DISCONNECT",
  HANDLE_ERROR: "HANDLE_ERROR",
  SET_MODAL_ERROR: "SET_MODAL_ERROR",
  HANDLE_PUBLISH_VIDEO: "HANDLE_PUBLISH_VIDEO",
  SET_CONNECTION_DATA: "SET_CONNECTION_DATA",
  TOGGLE_MODAL: "TOGGLE_MODAL",
  HANDLE_INPUT: "HANDLE_INPUT",
  SET_ROOM: "SET_ROOM",
  SET_CONNECTING: "SET_CONNECTING",
}
